# https://resilience4j.readme.io/docs/getting-started-3
resilience4j:
  retry:
    retry-aspect-order: 200 # 表示重试的的优先级，越小优先级越高
    backends:
      retryA:
        maxRetryAttempts: 5 # 重试次数
        waitDuration: 1000 # 重试的间隔时间
        retryExceptions: # 发生那些异常进行重试
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cbA:
        failureRateThreshold: 50 # 失败请求百分比，超过这个比例，CircuitBreaker就会变成OPEN状态
        permittedNumberOfCallsInHalfOpenState: 5 # 当CircuitBreaker处于HALF_OPEN状态的时候，允许通过的请求数量
        waitDurationInOpenState: 5s # 从OPEN状态变成HALF_OPEN状态需要的等待时间
        slidingWindowSize: 5 # 滑动窗口类型，COUNT_BASED代表是基于计数的滑动窗口，TIME_BASED代表是基于计时的滑动窗口
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5 # 最小请求个数。只有在滑动窗口内，请求个数达到这个个数，才会触发CircuitBreaker对于是否打开断路器的判断。
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.lang.RuntimeException
    circuit-breaker-aspect-order: 190
spring:
  application:
    name: resilience4j
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
